import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {

    private currentLang = new BehaviorSubject<string>('es');
    public currentLang$ = this.currentLang.asObservable();

    private dictionary: any = {
        'es': {
            'Home': 'Inicio',
            'Shop': 'Tienda',
            'Pages': 'Páginas',
            'Contact': 'Contacto',
            'Others pages': 'Otras páginas',
            'Account pages': 'Páginas de cuenta',
            'Checkout page': 'Página de pago',
            'Login': 'Ingresar',
            'Register': 'Registrarse',
            'Forgot password': 'Olvidé contraseña',
            'My Account': 'Mi Cuenta',
            'Wishlist': 'Lista de Deseos',
            'Order complete': 'Orden completa',
            'Payment': 'Pago',
            'Track order': 'Rastrear orden',
            'About us': 'Sobre nosotros',
            'Contact us': 'Contáctanos',
            'List view': 'Vista de lista',
            'Grid view': 'Vista de cuadrícula',
            'Shopping cart': 'Carrito de compras',
            'Product view': 'Vista de producto',
            'All categories': 'Todas las categorías',
            'Search': 'Buscar',
            'Cart': 'Carrito',
            'Language': 'Idioma',
            'Currency': 'Moneda',
            'Hello': 'Hola',
            'Welcome': 'Bienvenido',
            'Log out': 'Cerrar sesión',
            'Theme': 'Tema',
            'English': 'Inglés',
            'Spanish': 'Español',
            'FAQ': 'Preguntas Frecuentes',
            'Login if you are a returning customer': 'Inicie sesión si ya es cliente nuestro',
            'Email Address': 'Correo Electrónico',
            'Password': 'Clave',
            'Remember Me': 'Recuérdame',
            'Forgot Password?': '¿Olvidó su contraseña?',
            'Or login in with': 'O inicie sesión con',
            'Don\'t have an account?': '¿No tiene cuenta?',
            'Register Now': 'Regístrese Ahora',
            'Create an account': 'Crear una cuenta',
            'Register here if you are a new customer.': 'Regístrese aquí si es un cliente nuevo.',
            'First Name': 'Nombre',
            'Last Name': 'Apellido',
            'Repeat Password': 'Confirmar Clave',
            'I have read and agree to the': 'He leído y acepto los',
            'terms & conditions': 'términos y condiciones',
            'create account': 'crear cuenta',
            'Or singup in with': 'O regístrese con',
            'Already have an account?': '¿Ya tiene cuenta?',
            'Login Now': 'Inicie Sesión',
            'type password': 'escribir contraseña',
            'confirm your password': 'confirme su clave',
            'Jone': 'Juan',
            'Doe': 'Pérez',
            'Personal Information': 'Información Personal',
            'Enter your first name': 'Ingrese su nombre',
            'Enter your last name': 'Ingrese su apellido',
            'Birthday': 'Cumpleaños',
            'Gender': 'Género',
            'Male': 'Masculino',
            'Female': 'Femenino',
            'Other': 'Otro',
            'Enter your email': 'Ingrese su correo electrónico',
            'Phone Number': 'Número de Teléfono',
            'Enter your phone number': 'Ingrese su número de teléfono',
            'Upload your avatar': 'Sube tu foto de perfil',
            'Choose file': 'Seleccionar archivo',
            'Save Changes': 'Guardar Cambios',
            'Account Management': 'Gestión de Cuenta',
            'Profile Information': 'Información del Perfil',
            'Manage Addresses': 'Gestionar Direcciones',
            'Change Password': 'Cambiar Contraseña',
            'My Order History': 'Historial de Órdenes',
            'My Orders': 'Mis Órdenes',
            'My Reviews': 'Mis Reseñas',
            'Welcome back': 'Bienvenido de nuevo',
            'Happy Birthday!': '¡Feliz Cumpleaños!',
            'Saved Addresses': 'Direcciones Guardadas',
            'Add New': 'Agregar Nueva',
            'Address': 'Dirección',
            'Select': 'Seleccionar',
            'Edit Address': 'Editar Dirección',
            'Address Details': 'Detalles de la Dirección',
            'Company Name (Optional)': 'Nombre de la Empresa (Opcional)',
            'Country/Region': 'País/Región',
            'Town/City': 'Ciudad/Pueblo',
            'Street Address': 'Dirección de la Calle',
            'Zip Code': 'Código Postal',
            'ADD ADDRESS': 'AGREGAR DIRECCIÓN',
            'Security Settings': 'Configuración de Seguridad',
            'Update your password and manage account security.': 'Actualice su contraseña y gestione la seguridad de la cuenta.',
            'Current Password': 'Contraseña Actual',
            'Enter current password': 'Ingrese contraseña actual',
            'New Password': 'Nueva Contraseña',
            'Enter new password': 'Ingrese nueva contraseña',
            'Confirm New Password': 'Confirmar Nueva Contraseña',
            'Repeat your new password': 'Repita su nueva contraseña',
            'Two-Factor Authentication (2FA)': 'Autenticación de Dos Factores (2FA)',
            'Secure Your Account': 'Proteja Su Cuenta',
            'Add an extra layer of security to your account by enabling 2FA.': 'Agregue una capa extra de seguridad a su cuenta.',
            'Enabled': 'Habilitado',
            'Disabled': 'Deshabilitado',
            '2FA is active.': '2FA está activo.',
            'You will be asked for a verification code when signing in from unrecognized devices.': 'Se pedirá un código al iniciar desde dispositivos nuevos.',
            'Enter your email address and we will send you a link to reset your password.': 'Ingrese su correo electrónico y le enviaremos un enlace para restablecer su contraseña.',
            'Select your email': 'Escribe tu correo',
            'Send Reset Link': 'Enviar Enlace de Recuperación',
            'Sending...': 'Enviando...',
            'Back to Login': 'Volver al Inicio de Sesión',
            'Reset Password': 'Restablecer Contraseña',
            'Create a new, strong password for your account': 'Cree una contraseña nueva y segura para su cuenta',
            'Save New Password': 'Guardar Nueva Contraseña',
            'Saving...': 'Guardando...',
            'Invalid password reset link.': 'El enlace de recuperación es inválido.',
            'Please fill all fields.': 'Por favor llene todos los campos.',
            'Passwords do not match.': 'Las contraseñas no coinciden.',
            'Password must be at least 8 characters.': 'La contraseña debe tener al menos 8 caracteres.',
            'We have emailed your password reset link!': '¡Hemos enviado el enlace de recuperación a su correo!',
            "We can't find a user with that email address.": 'No podemos encontrar un usuario con ese correo electrónico.'
        },
        'en': {
            'Home': 'Home',
            'Shop': 'Shop',
            'Pages': 'Pages',
            'Contact': 'Contact',
            'Others pages': 'Others pages',
            'Account pages': 'Account pages',
            'Checkout page': 'Checkout page',
            'Login': 'Login',
            'Register': 'Register',
            'Forgot password': 'Forgot password',
            'My Account': 'My Account',
            'Wishlist': 'Wishlist',
            'Order complete': 'Order complete',
            'Payment': 'Payment',
            'Track order': 'Track order',
            'About us': 'About us',
            'Contact us': 'Contact us',
            'List view': 'List view',
            'Grid view': 'Grid view',
            'Shopping cart': 'Shopping cart',
            'Product view': 'Product view',
            'All categories': 'All categories',
            'Search': 'Search',
            'Cart': 'Cart',
            'Language': 'Language',
            'Currency': 'Currency',
            'Hello': 'Hello',
            'Welcome': 'Welcome',
            'Log out': 'Log out',
            'Theme': 'Theme',
            'English': 'English',
            'Spanish': 'Spanish',
            'FAQ': 'FAQ',
            'Login if you are a returning customer': 'Login if you are a returning customer',
            'Email Address': 'Email Address',
            'Password': 'Password',
            'Remember Me': 'Remember Me',
            'Forgot Password?': 'Forgot Password?',
            'Or login in with': 'Or login in with',
            'Don\'t have an account?': 'Don\'t have an account?',
            'Register Now': 'Register Now',
            'Create an account': 'Create an account',
            'Register here if you are a new customer.': 'Register here if you are a new customer.',
            'First Name': 'First Name',
            'Last Name': 'Last Name',
            'Repeat Password': 'Repeat Password',
            'I have read and agree to the': 'I have read and agree to the',
            'terms & conditions': 'terms & conditions',
            'create account': 'create account',
            'Or singup in with': 'Or sign up with',
            'Already have an account?': 'Already have an account?',
            'Login Now': 'Login Now',
            'type password': 'type password',
            'confirm your password': 'confirm your password',
            'Jone': 'John',
            'Doe': 'Doe',
            'Personal Information': 'Personal Information',
            'Enter your first name': 'Enter your first name',
            'Enter your last name': 'Enter your last name',
            'Birthday': 'Birthday',
            'Gender': 'Gender',
            'Male': 'Male',
            'Female': 'Female',
            'Other': 'Other',
            'Enter your email': 'Enter your email',
            'Phone Number': 'Phone Number',
            'Enter your phone number': 'Enter your phone number',
            'Upload your avatar': 'Upload your avatar',
            'Choose file': 'Choose file',
            'Save Changes': 'Save Changes',
            'Account Management': 'Account Management',
            'Profile Information': 'Profile Information',
            'Manage Addresses': 'Manage Addresses',
            'Change Password': 'Change Password',
            'My Order History': 'My Order History',
            'My Orders': 'My Orders',
            'My Reviews': 'My Reviews',
            'Welcome back': 'Welcome back',
            'Happy Birthday!': 'Happy Birthday!',
            'Saved Addresses': 'Saved Addresses',
            'Add New': 'Add New',
            'Address': 'Address',
            'Select': 'Select',
            'Edit Address': 'Edit Address',
            'Address Details': 'Address Details',
            'Company Name (Optional)': 'Company Name (Optional)',
            'Country/Region': 'Country/Region',
            'Town/City': 'Town/City',
            'Street Address': 'Street Address',
            'Zip Code': 'Zip Code',
            'ADD ADDRESS': 'ADD ADDRESS',
            'Security Settings': 'Security Settings',
            'Update your password and manage account security.': 'Update your password and manage account security.',
            'Current Password': 'Current Password',
            'Enter current password': 'Enter current password',
            'New Password': 'New Password',
            'Enter new password': 'Enter new password',
            'Confirm New Password': 'Confirm New Password',
            'Repeat your new password': 'Repeat your new password',
            'Two-Factor Authentication (2FA)': 'Two-Factor Authentication (2FA)',
            'Secure Your Account': 'Secure Your Account',
            'Add an extra layer of security to your account by enabling 2FA.': 'Add an extra layer of security to your account by enabling 2FA.',
            'Enabled': 'Enabled',
            'Disabled': 'Disabled',
            '2FA is active.': '2FA is active.',
            'You will be asked for a verification code when signing in from unrecognized devices.': 'You will be asked for a verification code when signing in from unrecognized devices.',
            'Enter your email address and we will send you a link to reset your password.': 'Enter your email address and we will send you a link to reset your password.',
            'Select your email': 'Select your email',
            'Send Reset Link': 'Send Reset Link',
            'Sending...': 'Sending...',
            'Back to Login': 'Back to Login',
            'Reset Password': 'Reset Password',
            'Create a new, strong password for your account': 'Create a new, strong password for your account',
            'Save New Password': 'Save New Password',
            'Saving...': 'Saving...',
            'Invalid password reset link.': 'Invalid password reset link.',
            'Please fill all fields.': 'Please fill all fields.',
            'Passwords do not match.': 'Passwords do not match.',
            'Password must be at least 8 characters.': 'Password must be at least 8 characters.',
            'We have emailed your password reset link!': 'We have emailed your password reset link!',
            "We can't find a user with that email address.": "We can't find a user with that email address."
        }
    };

    constructor() { }

    changeLanguage(lang: string) {
        this.currentLang.next(lang);
    }

    translate(key: string): string {
        const lang = this.currentLang.value;
        return this.dictionary[lang][key] || key;
    }
}
